name: Welcome
on:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRST_ISSUE: |
            👋 @{{ author }}
            Welcome to the Random APIs repository!🚀⚡
            Thank you and congrats🎉 for opening your very first issue in this project.
            Please make sure not to start working on the issue, unless you get assigned to it.😄

          FIRST_PR: |
            👋 @{{ author }}
            Welcome to the Random APIs repository!💖 
            Thank you and congrats🎉 for opening your first pull request. Please make sure you have followed our [Contributing Guidelines](https://github.com/ashutoshkrris/Random-APIs#how-to-contribute).
            🙌🙌 We will get back to you as soon as we can 😄.

          FIRST_PR_MERGED: |
            🎉 @{{ author }}
            Congratulations on merging your first pull request!
